services:
  tylersbot:
    image: tylersfoot/tylersbot:latest
    build:
      context: .
    container_name: tylersbot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OSU_CLIENT_ID=${OSU_CLIENT_ID}
      - OSU_CLIENT_SECRET=${OSU_CLIENT_SECRET}
    volumes:
      - ${BOT_DATA_PATH:-./data}:/app/data
